# Generated by Django 4.2.1 on 2023-10-29 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newuser',
            old_name='vioivodeship',
            new_name='voivodeship',
        ),
    ]
