# Generated by Django 4.2.1 on 2023-11-12 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_newuser_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='user_name',
        ),
    ]
