# Generated by Django 4.2.1 on 2023-10-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, unique=True, upload_to='uploads/')),
                ('counter', models.IntegerField(default=0)),
            ],
        ),
    ]
