# Generated by Django 4.2.1 on 2024-01-11 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Subjects', '0002_alter_subjects_options_subjects_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='counter',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='file',
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('file', models.FileField(blank=True, null=True, unique=True, upload_to='uploads/')),
                ('counter', models.IntegerField(blank=True, default=0)),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Subjects.subjects')),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
            },
        ),
    ]
