# Generated by Django 4.2.1 on 2024-01-11 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subjects', '0003_remove_subjects_counter_remove_subjects_file_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='semester',
            field=models.IntegerField(default=0),
        ),
    ]
