# Generated by Django 4.2.1 on 2024-01-16 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Subjects', '0004_subjects_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='FOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'FOS',
                'verbose_name_plural': 'FOSs',
            },
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='field_of_study',
        ),
        migrations.AddField(
            model_name='subjects',
            name='FOS_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Subjects.fos'),
        ),
    ]
