# Generated by Django 4.2.1 on 2024-01-16 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Subjects', '0006_alter_subjects_fos_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjects',
            old_name='FOS_id',
            new_name='FOS',
        ),
    ]
