# Generated by Django 4.2.1 on 2024-01-16 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subjects', '0007_rename_fos_id_subjects_fos'),
    ]

    operations = [
        migrations.AddField(
            model_name='fos',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
