# Generated by Django 4.2.1 on 2024-01-16 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Subjects', '0008_fos_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fos',
            options={'verbose_name': 'FOS', 'verbose_name_plural': 'FOS'},
        ),
    ]
