# Generated by Django 4.2.1 on 2024-01-16 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Subjects', '0009_alter_fos_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.RenameModel(
            old_name='FOS',
            new_name='FieldsOfStudy',
        ),
        migrations.RenameField(
            model_name='subjects',
            old_name='FOS',
            new_name='FieldsOfStudy',
        ),
        migrations.RemoveField(
            model_name='files',
            name='subject_id',
        ),
        migrations.AddField(
            model_name='files',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Subjects.subjects'),
        ),
        migrations.AddField(
            model_name='files',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Subjects.projects'),
        ),
    ]
