# Generated by Django 4.2.1 on 2024-01-19 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subjects', '0011_filesproject_filessubject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='semester',
            field=models.IntegerField(choices=[(1, 'Semestr 1'), (2, 'Semestr 2'), (3, 'Semestr 3'), (4, 'Semestr 4'), (5, 'Semestr 5'), (6, 'Semestr 6'), (7, 'Semestr 7')], default=1),
        ),
    ]
