# Generated by Django 5.1.2 on 2024-11-02 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Subjects", "0012_alter_subjects_semester"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subjects",
            options={},
        ),
    ]
