# Generated by Django 5.1.2 on 2025-02-17 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Subjects", "0014_department"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Department",
        ),
    ]
